<?php
$product = $block->getProduct();
$collections = $block->getTests();
?>


<html>
<head>
	<style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        * {
            box-sizing: border-box
        }

        input[type=text],
        input[type=email],
        input[type=password],
        input[type=tel] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 0 0;
            display: inline-block;
            border: none;
            background: lightgrey;
        }

        input[type=submit] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 0 0;
            display: inline-block;
            border: none;
            background: lightgrey;
        }


        input[type=text]:focus,
        input[type=email]:focus,
        input[type=password]:focus,
        input[type=tel]:focus,
        input[type=submit]:focus {
            background-color: darkgray;
            outline: none;
        }
        .div-class {
            width: 50%;
            padding: 15px;
            margin: auto;
        }
    </style>
    
    <script>
        function c_validation() {
            var name =
                document.forms.RegForm.name.value;
            var email =
                document.forms.RegForm.email.value;
            var question =
                document.forms.RegForm.question.value;

            var regEmail = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/g; //Javascript reGex for Email Validation.
            var regQuestion = /^[7-9]\d{9}$/; // Javascript reGex for Phone Number validation.
            var regName = /\d+$/g; // Javascript reGex for Name validation
            var regPassword = password;

            //name
            if (name == "" || regName.test(name)) {
                window.alert("Please enter your Name Properly.");
                // name.focus();
                return false;
            }
            //email
            if (email == "" || !regEmail.test(email)) {
                window.alert("Please enter a valid E-mail address..");
                // email.focus();
                return false;
            }
            //mobile number
            if (question == "" || !regQuestion.test(question)) {
                window.alert("Type your Quetions here..");
                // mobile.focus();
                return false;
            }
            return true;
        }
    </script>
        <?php
            foreach ($collections as $collection){
        ?>
            <td class="col question">
        <?php echo $collection->getData('question') . '<br>';
        ?>
            </td>
        <?php } ?>

</head>

<body>
   
    <form name="RegForm" method="post" id="RegForm" form class="RegForm" data-mage-init='{"validation":{}}' action=<?php echo $block->getUrl('customerfaq/index/save'); ?>>
        <div class="div-class">

            <input type="hidden" name="prod" id="prod" value="<?php echo $currentProduct->getId(); ?>
" placeholder="Product Id">
            <label for="name"><b>Name <s style="color: tomato;">*</s></b></label>
            <input type="text" placeholder="Please Enter Name" name="name" id="name" data-validate='{"required":true}'>
                
            <br></br><label for="email"><b>Email <s style="color: red">*</s></b></label>
            <input type="email" placeholder="Please Enter Email" name="email" data-validate='{"required":true}'>

            <br></br><label for="question"><b>Questions <s style="color: red">*</s></b></label>
            <input type="text" placeholder="What you Wanna Know Just Ask" name="question" data-validate='{"required":true}'>

            <br></br><input type="submit" value="Submit" name="submit" onclick="return c_validation()"/>
        </div>
    </form>

</body>

</html>




