<!DOCTYPE html>
<!-- <html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title> -->

  <style type="text/css">

  </style>
</head>
<body>
<div class="container">
    <form action="thanks.html" id="form" class="form">
        <h2>Registration Form</h2>
        <div class="form-control">
            <label for="name">Name:</label><br></br>
            <input type="text" id="name" name="name" placeholder="Enter username..">
            <small style="color: red">Username must be at least 3 characters</small><br></br>
        </div>
        <div class="form-control">
            <label for="email">Email:</label><br></br>
            <input type="text" id="email" name="email" placeholder="Enter email address..">
            <small style="color: red">Email cannot be empty</small><br></br>
        </div>
        <div class="form-control">
            <label for="email">Mobile:</label><br></br>
            <input type="text" id="mobile" name="mobile" placeholder="Enter your mobile number..">
            <small style="color: red">Mobile number cannot be empty</small><br></br>
        </div>
        <div class="form-control">
            <label for="password">Password:</label><br></br>
            <input type="password" id="password" name="password" placeholder="Enter password..">
            <small style="color: red">Password must be 8 or more characters</small><br></br>
        </div>
        <div class="form-control">
            <label for="password-confirmation">Confirm Password:</label><br></br>
            <input type="password" id="password-confirmation" name="password-confirmation" placeholder="Enter password again">
            <small style="color: red">Passwords must match</small><br></br>
        </div>
        <button class= "btn btn-primary" type="submit" style="color: red;">Submit</button>
    </form>
</div>
</body>
<!-- </html> -->

<script type="text/javascript">
  const form = document.querySelector("#form");
const username = document.querySelector("#username");
const email = document.querySelector("#email");
const password = document.querySelector("#password");
const passwordConfirmation = document.querySelector("#password-confirmation");

const showError = (input, msg) => {
    const formControl = input.parentElement;
    const small = formControl.querySelector("small");
    formControl.classList.add("error");
    small.textContent = msg;
};

const showSuccess = (input) => {
    const formControl = input.parentElement;
    formControl.classList.add("success");
};

const checkEmail = (input) => {
    const re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    if (re.test(input)) {
        showSuccess(input);
    } else {
        showError(input, "Email address is invalid. ");
    }
};

const checkPasswordMatch = (input1, input2) => {
    if (input1.value !== input2.value) {
        showError(input1, "Passwords must match");
    } else {
        showSuccess(input1);
    }
};

const getFieldName = (input) => {
    const firstLetter = input.id.charAt(0).toUpperCase();
    return firstLetter + input.id.slice(1);
};

const checkLength = (input, min, max) => {
    if (input.value.length < min || input.value.length > max) {
        showError(
            input,
            `${getFieldName(
                input
            )} must be between ${min} and ${max} characters long`
        );
    }
};

const checkRequired = (inputArr) => {
    inputArr.forEach((input) => {
        if (input.value.trim() === "") {
            showError(input, `${getFieldName(input)} is required`);
        } else {
            showSuccess(input);
        }
    });
};

const validateForm = () => {
    checkRequired([username, email, password, passwordConfirmation]);
    checkLength(username, 3, 20);
    checkLength(password, 8, 30);
    checkEmail(email);
    checkPasswordMatch(passwordConfirmation, password);
};

form.addEventListener("submit", function (e) {
    e.preventDefault();
    validateForm();
});

</script>