<!DOCTYPE html>
<html>
<body>
	<section class="regular slider">
		<div>
			<img src="http://magento241.com/media/catalog/product/cache/fbe7f0fc78fafc89505d8e3a27b8914e/b/o/book.jpeg" />
		</div>
		<div>
			<img src="http://magento241.com/media/catalog/product/cache/fbe7f0fc78fafc89505d8e3a27b8914e/i/p/iphone-14-png-image.png" />
		</div>
		<div>
			<img src="http://magento241.com/media/catalog/product/cache/fbe7f0fc78fafc89505d8e3a27b8914e/b/o/book_2.jpeg" />
		</div>
		<div>
			<img src="http://magento241.com/media/catalog/product/cache/fbe7f0fc78fafc89505d8e3a27b8914e/l/e/lenovolegion.jpg" />
		</div>
		<div>
			<img src="http://magento241.com/media/catalog/product/cache/fbe7f0fc78fafc89505d8e3a27b8914e/b/a/bag-ixrl2bqa_-transformed_1.png" />
		</div>
		<!-- <div>
			<img src="http://placehold.it/350x300?text=6" />
		</div> -->
	</section>
</body>
</html>